HOST = "127.0.0.1"
PORT = 65432
HEADER = 64
FORMAT = 'utf-8'
DISCON_MSG = '!DISCON'
GLOBAL_MSG = '!GLOBAL'
OBJECT_MSG = '!OBJECT'
STR_MSG = '!STR'
LOGIN_MSG = '!LOGIN'
AUTH_MSG = '!AUTH'

USERNAME_LIMIT = 20
